name: CI/CD 파이프라인

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Python 설정
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Python 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-cors flask-sock torch soundfile numpy
        pip install git+https://github.com/openai/whisper.git
    
    - name: Node.js 설정
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: 프론트엔드 의존성 설치
      run: |
        cd frontend/audio-client
        npm install
    
    - name: 프론트엔드 빌드
      run: |
        cd frontend/audio-client
        npm run build
        mkdir -p ../../backend/www
        cp -r build/* ../../backend/www/
    
    - name: ngrok 설치
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar xvzf ngrok-v3-stable-linux-amd64.tgz
        chmod +x ngrok
    
    - name: 애플리케이션 실행 및 ngrok 터널 열기
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        ./ngrok config add-authtoken $NGROK_AUTH_TOKEN
        cd backend
        python app.py &
        sleep 5
        ../ngrok http 3000 --log=stdout > ngrok.log &
        sleep 5
        NGROK_URL=$(grep -o 'https://.*\.ngrok-free\.app' ngrok.log | head -n 1)
        echo "애플리케이션이 다음 URL에서 5분간 접속 가능합니다: $NGROK_URL"
        echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV
    
    - name: 테스트 URL 출력
      run: |
        echo "애플리케이션 URL: ${{ env.NGROK_URL }}"
        echo "5분 후 URL은 만료됩니다. 테스트를 서둘러 진행해 주세요."
        sleep 300 